package com.avvsoft2050.coincryptoinfo.pojo

import androidx.room.Entity
import androidx.room.Ignore

@Entity(tableName = "favorite_coins")
class FavoriteCoins(
    id: String,
    symbol: String,
    name: String?,
    image: String?,
    currentPrice: Double?,
    marketCap: Long?,
    marketCapRank: Int?,
    fullyDilutedValuation: Long?,
    totalVolume: Long?,
    high24h: Double?,
    low24h: Double?,
    priceChange24h: Double?,
    priceChangePercentage24h: Double?,
    marketCapChange24h: Double?,
    marketCapChangePercentage24h: Double?,
    circulatingSupply: Double?,
    totalSupply: Double?,
    maxSupply: Double?,
    ath: Double?,
    athChangePercentage: Double?,
    athDate: String?,
    atl: Double?,
    atlChangePercentage: Double?,
    atlDate: String?,
    lastUpdated: String?,
    priceChangePercentage14dInCurrency: Double?,
    priceChangePercentage1hInCurrency: Double?,
    priceChangePercentage1yInCurrency: Double?,
    priceChangePercentage200dInCurrency: Double?,
    priceChangePercentage24hInCurrency: Double?,
    priceChangePercentage30dInCurrency: Double?,
    priceChangePercentage7dInCurrency: Double?
) : Coins(
    id,
    symbol,
    name,
    image,
    currentPrice,
    marketCap,
    marketCapRank,
    fullyDilutedValuation,
    totalVolume,
    high24h,
    low24h,
    priceChange24h,
    priceChangePercentage24h,
    marketCapChange24h,
    marketCapChangePercentage24h,
    circulatingSupply,
    totalSupply,
    maxSupply,
    ath,
    athChangePercentage,
    athDate,
    atl,
    atlChangePercentage,
    atlDate,
    lastUpdated,
    priceChangePercentage14dInCurrency,
    priceChangePercentage1hInCurrency,
    priceChangePercentage1yInCurrency,
    priceChangePercentage200dInCurrency,
    priceChangePercentage24hInCurrency,
    priceChangePercentage30dInCurrency,
    priceChangePercentage7dInCurrency
)
{
    @Ignore
    public constructor(coins:Coins) : this
        (coins.id,
        coins.symbol,
        coins.name,
        coins.image,
        coins.currentPrice,
        coins.marketCap,
        coins.marketCapRank,
        coins.fullyDilutedValuation,
        coins.totalVolume,
        coins.high24h,
        coins.low24h,
        coins.priceChange24h,
        coins.priceChangePercentage24h,
        coins.marketCapChange24h,
        coins.marketCapChangePercentage24h,
        coins.circulatingSupply,
        coins.totalSupply,
        coins.maxSupply,
        coins.ath,
        coins.athChangePercentage,
        coins.athDate,
        coins.atl,
        coins.atlChangePercentage,
        coins.atlDate,
        coins.lastUpdated,
        coins.priceChangePercentage14dInCurrency,
        coins.priceChangePercentage1hInCurrency,
        coins.priceChangePercentage1yInCurrency,
        coins.priceChangePercentage200dInCurrency,
        coins.priceChangePercentage24hInCurrency,
        coins.priceChangePercentage30dInCurrency,
        coins.priceChangePercentage7dInCurrency)

}