package com.avvsoft2050.coincryptoinfo.pojo

import androidx.room.Entity

@Entity(tableName = "favorite_coins_markets")
class FavoriteCoinsMarkets(
    id: String?,
    symbol: String,
    name: String?,
    image: String?,
    currentPrice: Double?,
    marketCap: Long?,
    marketCapRank: Int?,
    fullyDilutedValuation: Long?,
    totalVolume: Long?,
    high24h: Double?,
    low24h: Double?,
    priceChange24h: Double?,
    priceChangePercentage24h: Double?,
    marketCapChange24h: Double?,
    marketCapChangePercentage24h: Double?,
    circulatingSupply: Double?,
    totalSupply: Double?,
    maxSupply: Double?,
    ath: Double?,
    athChangePercentage: Double?,
    athDate: String?,
    atl: Double?,
    atlChangePercentage: Double?,
    atlDate: String?,
    lastUpdated: String?,
    priceChangePercentage14dInCurrency: Double?,
    priceChangePercentage1hInCurrency: Double?,
    priceChangePercentage1yInCurrency: Double?,
    priceChangePercentage200dInCurrency: Double?,
    priceChangePercentage24hInCurrency: Double?,
    priceChangePercentage30dInCurrency: Double?,
    priceChangePercentage7dInCurrency: Double?
) : CoinsMarkets(
    id,
    symbol,
    name,
    image,
    currentPrice,
    marketCap,
    marketCapRank,
    fullyDilutedValuation,
    totalVolume,
    high24h,
    low24h,
    priceChange24h,
    priceChangePercentage24h,
    marketCapChange24h,
    marketCapChangePercentage24h,
    circulatingSupply,
    totalSupply,
    maxSupply,
    ath,
    athChangePercentage,
    athDate,
    atl,
    atlChangePercentage,
    atlDate,
    lastUpdated,
    priceChangePercentage14dInCurrency,
    priceChangePercentage1hInCurrency,
    priceChangePercentage1yInCurrency,
    priceChangePercentage200dInCurrency,
    priceChangePercentage24hInCurrency,
    priceChangePercentage30dInCurrency,
    priceChangePercentage7dInCurrency
)